// Mocks generated by Mockito 5.4.6 from annotations
// in pokedex/test/lib/src/data/datasources/pokedex_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:core/core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex/pokedex.dart' as _i6;
import 'package:pokedex/src/data/datasources/pokedex_local_data_source.dart'
    as _i3;
import 'package:pokedex/src/data/models/request/pokemon_request.dart' as _i8;
import 'package:pokedex/src/data/models/response/pokemon_detail_response.dart'
    as _i5;
import 'package:pokedex/src/data/models/response/pokemon_response.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePokedexLocalDataSource_1 extends _i1.SmartFake
    implements _i3.PokedexLocalDataSource {
  _FakePokedexLocalDataSource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePokemonResponse_2 extends _i1.SmartFake
    implements _i4.PokemonResponse {
  _FakePokemonResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePokemonDetailResponse_3 extends _i1.SmartFake
    implements _i5.PokemonDetailResponse {
  _FakePokemonDetailResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PokedexRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokedexRemoteDatasourceImpl extends _i1.Mock
    implements _i6.PokedexRemoteDatasourceImpl {
  MockPokedexRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_0(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i2.ApiService);

  @override
  _i3.PokedexLocalDataSource get localDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#localDataSource),
            returnValue: _FakePokedexLocalDataSource_1(
              this,
              Invocation.getter(#localDataSource),
            ),
          )
          as _i3.PokedexLocalDataSource);

  @override
  _i7.Future<_i4.PokemonResponse> getPokemons(_i8.PokemonRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemons, [request]),
            returnValue: _i7.Future<_i4.PokemonResponse>.value(
              _FakePokemonResponse_2(
                this,
                Invocation.method(#getPokemons, [request]),
              ),
            ),
          )
          as _i7.Future<_i4.PokemonResponse>);

  @override
  _i7.Future<_i5.PokemonDetailResponse> getPokemonDetail(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonDetail, [name]),
            returnValue: _i7.Future<_i5.PokemonDetailResponse>.value(
              _FakePokemonDetailResponse_3(
                this,
                Invocation.method(#getPokemonDetail, [name]),
              ),
            ),
          )
          as _i7.Future<_i5.PokemonDetailResponse>);
}
